services:
  - type: web
    name: ppsa-dashboard
    env: python
    plan: free
    buildCommand: |
      pyenv install -s 3.11.9
      pyenv global 3.11.9
      pip install -r requirements.txt
    startCommand: gunicorn app:server
